### ISSUE TITLE
psutil.ZombieProcess process still exists but it's a zombie

### ISSUE THREAD

**Issue by cecilMao** [tomas789/kitti2bag#30]
Hi, when I converted the kitti data to bag file using kitti2bag, I met the following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/kitti2bag", line 16, in <module>
    import rosbag
  File "/opt/ros/melodic/lib/python2.7/site-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/opt/ros/melodic/lib/python2.7/site-packages/rosbag/bag.py", line 55, in <module>
    import gnupg
  File "/usr/local/lib/python2.7/site-packages/gnupg/__init__.py", line 23, in <module>
    from . import gnupg
  File "/usr/local/lib/python2.7/site-packages/gnupg/gnupg.py", line 42, in <module>
    from ._meta    import GPGBase
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 134, in <module>
    class GPGBase(object):
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 72, in __new__
    if cls._find_agent():
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 115, in _find_agent
    if (proc.name() == "gpg-agent") and proc.is_running():
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 610, in name
    cmdline = self.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 663, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 426, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 373, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil._exceptions.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=62522)
```

**Comment by tomas789** [comment]
Hi! Based on the stack trace, the error is caused by the `gnupg` package. I can see that you are using ROS on OS X which has only an [experimental support](http://wiki.ros.org/melodic/Installation) for ROS Melodic. My guess would be that on your installation, you won't be able to work with the rosbag files at all. At least from the python bindings. If that is true, you will get a better answer from the ROS communities then here. Let me know how that turned out.
