### ISSUE TITLE
the file "kitti_2011_09_26_drive_0002_synced.bag" is empty

### ISSUE THREAD

**Issue by zhongncku** [tomas789/kitti2bag#68]
Hi everyone, I was following the guidance utilizing kitti2bag to visualize the pcd, however recently face this problem, havent found ways to solve, pls help me, Thanks in advance
-------
**the terminal was run in this directory, which contains the following files:**
zhong1@ubuntu:~/visualize pcd$ ls
2011_09_26            
2011_09_26_drive_0005_sync.zip  
kitti2bag-master.zip
2011_09_26_calib.zip  
kitti2bag-master

**call the generating command:**
zhong1@ubuntu:~/visualize pcd$ kitti2bag -t 2011_09_26 -r 0002 raw_synced
Traceback (most recent call last):
  File "/usr/local/bin/kitti2bag", line 394, in <module>
    main()
  File "/usr/local/bin/kitti2bag", line 302, in main
    kitti = pykitti.raw(args.dir, args.date, args.drive)
  File "/home/zhong1/.local/lib/python3.8/site-packages/pykitti/raw.py", line 35, in __init__
    self._load_timestamps()
  File "/home/zhong1/.local/lib/python3.8/site-packages/pykitti/raw.py", line 253, in _load_timestamps
    with open(timestamp_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhong1/visualize pcd/2011_09_26/2011_09_26_drive_0002_sync/oxts/timestamps.txt'

->>successfully generated "kitti_2011_09_26_drive_0002_synced.bag" however that file is empty @@

**Comment by Magic-wei** [comment]
@zhongncku Looks like you downloaded the 0005 dataset instead of 0002 which was used in your command. Try `kitti2bag -t 2011_09_26 -r 0005 raw_synced` instead.
